version: "3"
services:
  web:
    image: ts-node:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 400M
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    networks:
      - webnet
networks:
  webnet:
