version: 2
jobs:
  build:
    working_directory: ~/typescript-node-example
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: update-npm
          command: "npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test-report
      - store_artifacts:
          path: test-results.txt
          prefix: tests
deployment:
  production:
    branch: master
    heroku:
      appname: typescript-node-example
