version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    working_directory: ~/typescript-node-example
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: update-npm
          command: "npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test-report
      - store_artifacts:
          path: test-results.txt
          prefix: tests
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
workflows:
  deploy:
    jobs:
      - build
      - deploy
